<a href="https://colab.research.google.com/github/surya-moorthy/Mlops/blob/main/torchNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors


In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.current_device()

0

In [ ]:
torch.cuda.device(0)

In [ ]:
t = torch.Tensor([1313,2,3])

In [ ]:
print(t.dtype)
print(t.device)
t.layout
print(t)

torch.float32
cpu
tensor([1313.,    2.,    3.])


In [ ]:
data = np.array([1,2,3,4,5])
type(data)

numpy.ndarray

In [ ]:
tensor_data = torch.tensor(data,dtype=torch.float32,requires_grad=True)
tensor_data

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [ ]:
device = torch.device('cuda:0')

In [ ]:
torch.tensor(data, device=device)

tensor([1, 2, 3, 4, 5], device='cuda:0')

## Autograd

In [ ]:
x = torch.randn(3,requires_grad=True)
x

tensor([ 0.2220,  1.7795, -0.5310], requires_grad=True)

In [ ]:
x = torch.randn(3,requires_grad=True)
y = x.sum()
print(x,y)
y.backward()
print(x.grad)

tensor([ 0.9283, -0.1552,  0.7338], requires_grad=True) tensor(1.5069, grad_fn=<SumBackward0>)


tensor([1., 1., 1.])

## Backpropogation

In [ ]:
x = torch.tensor(10.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0,requires_grad=True)

y_hat = w*x
loss = (y_hat-y)**2

print(loss)

loss.backward()
print(w.grad)

tensor(64., grad_fn=<PowBackward0>)
tensor(160.)
